# Generated by Django 4.2.5 on 2023-10-21 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0006_vendorfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorfollower',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
