# Generated by Django 4.2.5 on 2023-11-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0008_product_discount_price_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='store_name',
            new_name='shop_name',
        ),
    ]
