# Generated by Django 4.2.5 on 2023-11-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0009_rename_store_name_vendor_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos'),
        ),
    ]
