# Generated by Django 3.2.1 on 2023-11-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0013_product_product_brand_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
    ]
