# Generated by Django 3.2.1 on 2023-11-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0015_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='testify.Product'),
        ),
    ]
