# Generated by Django 3.2.1 on 2023-12-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0022_auto_20231210_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreview',
            name='rating',
            field=models.FloatField(),
        ),
    ]
