# Generated by Django 3.2.1 on 2023-12-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0023_alter_vendorreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreview',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='testify.vendor'),
        ),
    ]
