# Generated by Django 3.2.1 on 2023-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0024_alter_vendorreview_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
