# Generated by Django 3.2.1 on 2023-12-13 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0025_alter_vendorreview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
